#this file is not in use from 16/10/2025
#severity is now generated by LLM in detect_errors.py
# Keeping for backward compatibility but it's no longer used in the pipeline

from typing import List
from agents.classification_agent.src.utils import DetectedError

#keyword buckets for classificaiton
BUCKETS: dict[str, List[str]] = {
    "Critical": [
        "crash", "crashes", "crashing",
        "data loss", "lost data",
        "fails to login", "cannot login", "can't login", "login failure",
        "payment fails", "charge failed", "payment error",
        "outage", "downtime", "service down", "unavailable",
        "security breach", "leak", "p0",
    ],
    "Major": [
        "timeout", "very slow", "slow query", "latency",
        "duplicate charge", "overcharged", "billing mismatch",
        "token expires", "auth expires", "session expires",
        "inconsistent api", "breaking change", "backward incompatible",
        "webhook duplicate", "retry storm",
        "memory leak", "high cpu", "high cpu usage",
    ],
    "Minor": [
        "typo", "grammar", "layout shift", "overlapping",
        "button off-canvas", "alignment", "color contrast",
        "docs outdated", "example wrong", "missing example",
    ],
    "Suggestion": [
        "wish", "would be nice", "feature request",
        "could you add", "please add", "it would help if",
    ],
    "None": [],
}


def classify_criticality(err: DetectedError) -> str:
    s = f"{err.error_summary} {' '.join(err.error_type)}".lower()

    #priority order
    for level in ("Critical", "Major", "Minor", "Suggestion"):
        for kw in BUCKETS[level]:  
            if kw in s:
                return level  
            
    # typebased fallbacks this helps even if no keywords
    if "Crash" in err.error_type or "Billing" in err.error_type and "duplicate" in s:
        return "Critical"
    if "Performance" in err.error_type or "Auth" in err.error_type or "API" in err.error_type:
        return "Major"
    if "UI" in err.error_type or "Docs" in err.error_type:
        return "Minor"

    return "None"
